# Generated by Django 5.2.17 on 2026-09-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('format_name', models.TextField(blank=True, null=True)),
                ('sha256_checksum', models.BinaryField(unique=True)),
                ('date_added', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('original_filename', models.TextField(blank=True, null=True)),
                ('sheet_data_loaded', models.BooleanField(blank=True, null=True)),
                ('grd_data_loaded', models.BooleanField(blank=True, null=True)),
                ('issue_indiv_list', models.JSONField(blank=True, null=True)),
                ('issue_inventories_list', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_versions',
                'ordering': ['-date_added', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MappedTerm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('term', models.TextField(unique=True)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapped_terms',
                'ordering': ['term'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawTerm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('term', models.TextField(unique=True)),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'raw_terms',
                'ordering': ['term'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_name', models.TextField()),
                ('sheet_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sheets',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
