# Generated by Django 5.2.17 on 2026-09-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdiposeRef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'adipose_ref',
                'ordering': ['value'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstimatesTypeRef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'estimates_type_ref',
                'ordering': ['value'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GearRef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'gear_ref',
                'ordering': ['value'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdTypeRef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'id_type_ref',
                'ordering': ['value'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SexRef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'sex_ref',
                'ordering': ['value'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesRef',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'species_ref',
                'ordering': ['value'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
