# Generated by Django 5.2.17 on 2026-09-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsAndGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.TextField()),
                ('collection', models.TextField(blank=True, null=True)),
                ('collection_display_order', models.BigIntegerField(blank=True, null=True)),
                ('group_display_order', models.BigIntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collections_and_groups',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estimates_type', models.TextField()),
                ('point_estimate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('lower_credible_interval', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('upper_credible_interval', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('conservation_unit_code', models.TextField(blank=True, null=True)),
                ('conservation_unit_name', models.TextField(blank=True, null=True)),
                ('repunit', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estimates',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('indiv', models.TextField()),
                ('id_source', models.TextField(blank=True, null=True)),
                ('top_collection', models.TextField(blank=True, null=True)),
                ('top_collection_probability', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('catch_year', models.IntegerField(blank=True, null=True)),
                ('catch_date', models.DateField(blank=True, null=True)),
                ('catch_date_2', models.DateField(blank=True, null=True)),
                ('mgl_pid', models.TextField(blank=True, null=True)),
                ('mgl_pid_batch', models.TextField(blank=True, null=True)),
                ('sex_id', models.TextField(blank=True, null=True)),
                ('sex_note', models.TextField(blank=True, null=True)),
                ('stamp_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals',
                'ordering': ['id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualCollectionResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collection', models.TextField()),
                ('probability', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'individuals_collection_results',
                'ordering': ['-probability'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualCustomResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.TextField()),
                ('probability', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'individuals_custom_results',
                'ordering': ['-probability'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualDuplicate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_non_miss', models.IntegerField(blank=True, null=True)),
                ('num_match', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals_duplicates',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualInventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'individuals_inventories',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualNegativeSpecies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('negative_species_confirmed', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals_negative_species',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualPbt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attributes', models.JSONField()),
                ('pbt_brood_year', models.SmallIntegerField(blank=True, null=True)),
                ('pbt_brood_collection', models.TextField(blank=True, null=True)),
                ('pbt_brood_group', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals_pbt',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualPositiveSpecies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('positive_species_id', models.BigIntegerField()),
                ('pos_sp_id', models.IntegerField(blank=True, null=True)),
                ('pos_sp_id_proportion', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals_positive_species',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualRegionResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.TextField()),
                ('probability', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'individuals_region_results',
                'ordering': ['-probability'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualRepunitResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repunit', models.TextField()),
                ('probability', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'individuals_repunit_results',
                'ordering': ['-probability'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualRunData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('indiv', models.TextField(blank=True, null=True)),
                ('date_run', models.DateField(blank=True, null=True)),
                ('species_id', models.BigIntegerField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals_run_data_v',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sample_collection', models.TextField()),
                ('sample_code', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('area_fished', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'db_table': 'inventories',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryRunData',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sample_collection', models.TextField(blank=True, null=True)),
                ('date_run', models.DateField(blank=True, null=True)),
                ('species_id', models.BigIntegerField(blank=True, null=True)),
                ('species', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventories_run_data_v',
                'ordering': ['pk'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('species_id', models.BigIntegerField()),
                ('sha256', models.BinaryField()),
                ('original_filename', models.TextField()),
                ('ingestion_date', models.DateField()),
                ('pipeline_version', models.CharField(blank=True, max_length=255, null=True)),
                ('date_run', models.DateField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('baseline_file', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-ingestion_date', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBaselineFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repunit', models.TextField()),
                ('collection', models.TextField(blank=True, null=True)),
                ('cu', models.CharField(blank=True, max_length=255, null=True)),
                ('cu_name', models.TextField(blank=True, null=True)),
                ('display_order', models.BigIntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_baseline_files',
                'ordering': ['display_order', 'id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualExtraction',
            fields=[
                ('individual', models.OneToOneField(db_column='individuals_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='extraction', serialize=False, to='grd.individual')),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'individuals_extraction',
                'ordering': ['individual'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
